import time
import datetime
import addUserController as AUC
import errors as E
from PyQt5.QtGui import QCursor
import pharmacyLoginController as PLC
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon, QPixmap
class Ui_addUser(object):
    def __init__(self):
        global numberValidator,createDate,createDate2
        unix = time.time()
        createDate = str(datetime.datetime.fromtimestamp(unix).strftime('%Y-%m-%d %H:%M:%S'))
        createDate2 = str(datetime.datetime.fromtimestamp(unix).strftime('%Y-%m-%d'))
        numberValidator = QtGui.QIntValidator()

    def setupUi(self, Dialog):
        Dialog.setObjectName("adminPages")
        Dialog.setFixedSize(942, 594)
        self.setWindowFlags(QtCore.Qt.Window)
        self.setWindowFlag(QtCore.Qt.WindowCloseButtonHint, False)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 950, 81))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("header")
        self.backImg = QtWidgets.QLabel(self.frame)
        self.backImg.setGeometry(QtCore.QRect(30, 16, 40, 41))
        self.backImg.setObjectName("backImg")
        self.backImg.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        pixmap = QPixmap('data/images/back2.png')
        self.backImg.setPixmap(pixmap)
        self.backImg.setScaledContents(True)
        self.title = QtWidgets.QLabel(self.frame)
        self.title.setGeometry(QtCore.QRect(300, 20, 351, 50))
        self.title.setObjectName("pagesTitle")
        self.username = QtWidgets.QLabel(self.frame)
        self.username.setGeometry(QtCore.QRect(830, 20, 120, 50))
        self.username.setObjectName("usernameLabel")
        self.username.setText(str(PLC.pharmacyLoginController.getUsername()))

        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(300, 100, 20, 481))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(600, 100, 21, 291))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 84, 271, 20))
        self.label.setObjectName("searchLabel")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(340, 84, 271, 20))
        self.label_2.setObjectName("searchLabel")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(650, 84, 271, 20))
        self.label_3.setObjectName("searchLabel")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(19, 99, 281, 491))
        self.widget.setObjectName("widget")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 271, 31))
        self.label_4.setObjectName("staffLabel")
        self.uname = QtWidgets.QLineEdit(self.widget)
        self.uname.setGeometry(QtCore.QRect(0, 30, 271, 31))
        self.uname.setObjectName("uname")
        self.fName = QtWidgets.QLineEdit(self.widget)
        self.fName.setGeometry(QtCore.QRect(0, 100, 271, 31))
        self.fName.setObjectName("fName")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(0, 70, 271, 31))
        self.label_5.setObjectName("staffLabel")
        self.lName = QtWidgets.QLineEdit(self.widget)
        self.lName.setGeometry(QtCore.QRect(0, 170, 271, 31))
        self.lName.setObjectName("lName")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(0, 140, 271, 31))
        self.label_6.setObjectName("staffLabel")
        self.dob = QtWidgets.QDateEdit(self.widget)
        self.dob.setGeometry(QtCore.QRect(0, 240, 271, 31))
        self.dob.setObjectName("dob")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(0, 210, 271, 31))
        self.label_7.setObjectName("staffLabel")
        self.sex = QtWidgets.QComboBox(self.widget)
        self.sex.setGeometry(QtCore.QRect(0, 310, 271, 31))
        self.sex.setObjectName("sex")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(0, 280, 271, 31))
        self.label_8.setObjectName("staffLabel")
        self.status = QtWidgets.QComboBox(self.widget)
        self.status.addItem("Single")
        self.status.addItem("Divorced")
        self.status.addItem("Married")
        self.status.setGeometry(QtCore.QRect(0, 380, 271, 31))
        self.status.setObjectName("status")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(0, 350, 271, 31))
        self.label_9.setObjectName("staffLabel")
        self.kinName = QtWidgets.QLineEdit(self.widget)
        self.kinName.setGeometry(QtCore.QRect(0, 450, 271, 31))
        self.kinName.setObjectName("kinName")
        self.label_22 = QtWidgets.QLabel(self.widget)
        self.label_22.setGeometry(QtCore.QRect(0, 420, 271, 31))
        self.label_22.setObjectName("staffLabel")
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setGeometry(QtCore.QRect(320, 100, 281, 491))
        self.widget_2.setObjectName("widget_2")
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 271, 31))
        self.label_10.setObjectName("staffLabel")
        self.nationalID = QtWidgets.QLineEdit(self.widget_2)
        self.nationalID.setGeometry(QtCore.QRect(0, 30, 271, 31))
        self.nationalID.setObjectName("nationalID")
        self.homeDist = QtWidgets.QLineEdit(self.widget_2)
        self.homeDist.setGeometry(QtCore.QRect(0, 100, 271, 31))
        self.homeDist.setObjectName("homeDist")
        self.label_11 = QtWidgets.QLabel(self.widget_2)
        self.label_11.setGeometry(QtCore.QRect(0, 70, 271, 31))
        self.label_11.setObjectName("staffLabel")
        self.currentDist = QtWidgets.QLineEdit(self.widget_2)
        self.currentDist.setGeometry(QtCore.QRect(0, 170, 271, 31))
        self.currentDist.setObjectName("currentDist")
        self.label_12 = QtWidgets.QLabel(self.widget_2)
        self.label_12.setGeometry(QtCore.QRect(0, 140, 271, 31))
        self.label_12.setObjectName("staffLabel")
        self.currentAddress = QtWidgets.QLineEdit(self.widget_2)
        self.currentAddress.setGeometry(QtCore.QRect(0, 240, 271, 31))
        self.currentAddress.setObjectName("currentAddress")
        self.label_13 = QtWidgets.QLabel(self.widget_2)
        self.label_13.setGeometry(QtCore.QRect(0, 210, 271, 31))
        self.label_13.setObjectName("staffLabel")
        self.phone = QtWidgets.QLineEdit(self.widget_2)
        self.phone.setGeometry(QtCore.QRect(0, 310, 271, 31))
        self.phone.setObjectName("phone")
        self.phone.setValidator(numberValidator)
        self.label_14 = QtWidgets.QLabel(self.widget_2)
        self.label_14.setGeometry(QtCore.QRect(0, 280, 271, 31))
        self.label_14.setObjectName("staffLabel")
        self.yoEmail = QtWidgets.QLineEdit(self.widget_2)
        self.yoEmail.setGeometry(QtCore.QRect(0, 380, 271, 31))
        self.yoEmail.setObjectName("yoEmail")
        self.label_15 = QtWidgets.QLabel(self.widget_2)
        self.label_15.setGeometry(QtCore.QRect(0, 350, 271, 31))
        self.label_15.setObjectName("staffLabel")
        self.kinPhone = QtWidgets.QLineEdit(self.widget_2)
        self.kinPhone.setGeometry(QtCore.QRect(0, 450, 271, 31))
        self.kinPhone.setObjectName("kinPhone")
        self.kinPhone.setValidator(numberValidator)
        self.label_23 = QtWidgets.QLabel(self.widget_2)
        self.label_23.setGeometry(QtCore.QRect(0, 420, 271, 31))
        self.label_23.setObjectName("staffLabel")
        self.widget_3 = QtWidgets.QWidget(Dialog)
        self.widget_3.setGeometry(QtCore.QRect(620, 100, 281, 281))
        self.widget_3.setObjectName("widget_3")
        self.label_16 = QtWidgets.QLabel(self.widget_3)
        self.label_16.setGeometry(QtCore.QRect(0, 0, 271, 31))
        self.label_16.setObjectName("staffLabel")
        self.salary = QtWidgets.QLineEdit(self.widget_3)
        self.salary.setGeometry(QtCore.QRect(0, 30, 271, 31))
        self.salary.setObjectName("salary")
        self.salary.setValidator(numberValidator)
        self.joinDate = QtWidgets.QDateEdit(self.widget_3)
        self.joinDate.setGeometry(QtCore.QRect(0, 100, 271, 31))
        self.joinDate.setObjectName("joinDate")
        self.label_17 = QtWidgets.QLabel(self.widget_3)
        self.label_17.setGeometry(QtCore.QRect(0, 70, 271, 31))
        self.label_17.setObjectName("staffLabel")
        self.pass1 = QtWidgets.QLineEdit(self.widget_3)
        self.pass1.setGeometry(QtCore.QRect(0, 170, 271, 31))
        self.pass1.setObjectName("pass1")
        self.label_18 = QtWidgets.QLabel(self.widget_3)
        self.label_18.setGeometry(QtCore.QRect(0, 140, 271, 31))
        self.label_18.setObjectName("staffLabel")
        self.pass2 = QtWidgets.QLineEdit(self.widget_3)
        self.pass2.setGeometry(QtCore.QRect(0, 240, 271, 31))
        self.pass2.setObjectName("pass2")
        self.label_19 = QtWidgets.QLabel(self.widget_3)
        self.label_19.setGeometry(QtCore.QRect(0, 210, 271, 31))
        self.label_19.setObjectName("staffLabel")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(610, 380, 301, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.updateAccBTN = QtWidgets.QPushButton(Dialog)
        self.updateAccBTN.setGeometry(QtCore.QRect(650, 450, 221, 71))
        self.updateAccBTN.setObjectName("pagesBTN")
        self.updateAccBTN.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.updateAccBTN.clicked.connect(self.addUser)
        self.sex.addItem("Male")
        self.sex.addItem("Female")
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.username.setText(str(PLC.pharmacyLoginController.getUsername()))

    def addUser(self):
        uname = self.uname.text()
        fname = self.fName.text()
        lname = self.lName.text()
        dob = self.dob.text()
        sex = self.sex.currentText()
        status = self.status.currentText()
        natID = self.nationalID.text()
        homeD = self.homeDist.text()
        currentD = self.currentDist.text()
        currentAdd = self.currentAddress.text()
        phone = self.phone.text()
        email = self.yoEmail.text()
        kinName = self.kinName.text()
        kinPhone = self.kinPhone.text()
        salary = self.salary.text()
        pass1 = self.pass1.text()
        pass2 = self.pass2.text()
        joinDate = self.joinDate.text()

        uname = uname.lower()

        eObj = E.errors()

        if uname==""or fname==""or lname==""or kinName==""or kinPhone==""or phone==""or currentD==""or homeD==""or \
                currentAdd=="" or natID==""or pass1==""or pass2=="":
            eObj.errorBox('Error', 'Please fill all fields with *')
        elif pass2 != pass1:
            eObj.errorBox('Error', 'Passwords do not match')
        elif(AUC.addUserController.checkUsername(uname)==1):
            eObj.errorBox('Error', 'Username already taken,please change it')
        else:
            if (AUC.addUserController.storeUser(self, uname, fname, lname, dob, sex, status, natID,homeD,currentD,currentAdd,
                                                phone, email, kinName,kinPhone,salary,pass1,joinDate, createDate) == 1):
                eObj.success('Congratulations', 'New user has been added')
                self.addUserClear()
            else:
                eObj.errorBox('Error', 'Some thing went wrong and data has not been saved')

    def addUserClear(self):
        self.uname.setText("")
        self.fName.setText("")
        self.lName.setText("")
        #dob = self.dob.set
        self.sex.setCurrentIndex(0)
        self.status.setCurrentIndex(0)
        self.nationalID.setText("")
        self.homeDist.setText("")
        self.currentDist.setText("")
        self.currentAddress.setText("")
        self.phone.setText("")
        self.yoEmail.setText("")
        self.kinName.setText("")
        self.kinPhone.setText("")
        self.salary.setText("")
        self.pass1.setText("")
        self.pass2.setText("")
        #joinDate = self.joinDate.text()


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Staff Member | UG - Pharmacy Management System"))

        self.backImg.setText(_translate("Dialog", ""))
        self.title.setText(_translate("Dialog", "Add Staff Member"))
        self.username.setText(_translate("Dialog", "Username"))
        self.label.setText(_translate("Dialog", "Bio Data"))
        self.label_2.setText(_translate("Dialog", "Address And Contacts"))
        self.label_3.setText(_translate("Dialog", "Password Section"))
        self.label_4.setText(_translate("Dialog", "Username*"))
        self.label_5.setText(_translate("Dialog", "First Name*"))
        self.label_6.setText(_translate("Dialog", "Last Name*"))
        self.label_7.setText(_translate("Dialog", "Date Of Birth*"))
        self.label_8.setText(_translate("Dialog", "Sex*"))
        self.label_9.setText(_translate("Dialog", "Status*"))
        self.label_22.setText(_translate("Dialog", "Next Of Kin*"))
        self.label_10.setText(_translate("Dialog", "National ID*"))
        self.label_11.setText(_translate("Dialog", "Home District*"))
        self.label_12.setText(_translate("Dialog", "Current District*"))
        self.label_13.setText(_translate("Dialog", "Current Address*"))
        self.label_14.setText(_translate("Dialog", "Phone Number*"))
        self.label_15.setText(_translate("Dialog", "Email Address"))
        self.label_23.setText(_translate("Dialog", "Next Of Kin Contact*"))
        self.label_16.setText(_translate("Dialog", "Salary "))
        self.label_17.setText(_translate("Dialog", "Joining Date"))
        self.label_18.setText(_translate("Dialog", "Password*"))
        self.label_19.setText(_translate("Dialog", "Confirm Password*"))
        self.updateAccBTN.setText(_translate("Dialog", "ADD STAFF"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_addUser()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

