from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QCursor
import pharmacyLogin as PL
from PyQt5.QtGui import QIcon, QPixmap
class Ui_adminMenu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("adminMenuBody")
        MainWindow.setFixedSize(914, 594)
        self.setWindowFlag(QtCore.Qt.WindowCloseButtonHint, False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.img2 = QtWidgets.QLabel(self.centralwidget)

        pixmap = QPixmap('data/images/logoInner.png')
        self.img2.setPixmap(pixmap)
        self.img2.setGeometry(QtCore.QRect(50, 10, 121, 121))
        self.img2.setScaledContents(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.img2.setFont(font)
        self.img2.setScaledContents(True)
        self.img2.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 20, 500, 46))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("title1")
        self.logoutBTN = QtWidgets.QPushButton(self.centralwidget)
        self.logoutBTN.setGeometry(QtCore.QRect(770, 20, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.logoutBTN.setFont(font)
        self.logoutBTN.setObjectName("logoutBTN")
        self.logoutBTN.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 520, 920, 2))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("adminLine")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 540, 381, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("footerText")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setGeometry(QtCore.QRect(250, 100, 491, 30))
        self.label_2.setObjectName("header1")

        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 140, 811, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setObjectName("addDrug")
        pixmap = QPixmap('data/images/addDrug.png')
        pixmap = pixmap.scaledToWidth(90)
        self.label_9.setPixmap(pixmap)
        self.label_9.mousePressEvent = self.labelClick1
        self.label_9.setObjectName("gridImg")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout.addWidget(self.label_9)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_14.setObjectName("gridImg")
        pixmap = QPixmap('data/images/viewStock.png')
        pixmap = pixmap.scaledToWidth(88)
        self.label_14.setPixmap(pixmap)
        self.label_14.mousePressEvent = self.labelClick2
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout.addWidget(self.label_14)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName("gridImg")
        pixmap = QPixmap('data/images/viewSales.png')
        pixmap = pixmap.scaledToWidth(85)
        self.label_6.setPixmap(pixmap)
        self.label_6.mousePressEvent = self.labelClick3
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout.addWidget(self.label_6)

        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName("gridImg")
        pixmap = QPixmap('data/images/credit.png')
        pixmap = pixmap.scaledToWidth(90)
        self.label_7.setPixmap(pixmap)
        self.label_7.mousePressEvent = self.labelClick13
        self.label_7.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout.addWidget(self.label_7)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(50, 220, 811, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_24 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_24.setObjectName("gridText")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_2.addWidget(self.label_24)
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_17.setObjectName("gridText")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_2.addWidget(self.label_17)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_16.setObjectName("gridText")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_2.addWidget(self.label_16)

        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_8.setObjectName("gridText")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_2.addWidget(self.label_8)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(50, 350, 811, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_26 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_26.setObjectName("gridText")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_3.addWidget(self.label_26)
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_18.setObjectName("gridText")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_3.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_19.setObjectName("gridText")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_3.addWidget(self.label_19)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_11.setObjectName("gridText")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_3.addWidget(self.label_11)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(50, 270, 811, 81))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_25 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_25.setObjectName("gridImg")
        pixmap = QPixmap('data/images/viewExp.png')
        pixmap = pixmap.scaledToWidth(85)
        self.label_25.setPixmap(pixmap)
        self.label_25.mousePressEvent = self.labelClick5
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout_4.addWidget(self.label_25)
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_21.setObjectName("gridImg")
        pixmap = QPixmap('data/images/outStock.png')
        pixmap = pixmap.scaledToWidth(88)
        self.label_21.setPixmap(pixmap)
        self.label_21.mousePressEvent = self.labelClick6
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout_4.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_22.setObjectName("gridImg")
        pixmap = QPixmap('data/images/expire.png')
        pixmap = pixmap.scaledToWidth(88)
        self.label_22.setPixmap(pixmap)
        self.label_22.mousePressEvent = self.labelClick7
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout_4.addWidget(self.label_22)

        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_10.setObjectName("gridImg")
        pixmap = QPixmap('data/images/creditClear.png')
        pixmap = pixmap.scaledToWidth(88)
        self.label_10.setPixmap(pixmap)
        self.label_10.mousePressEvent = self.labelClick14
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout_4.addWidget(self.label_10)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(50, 400, 811, 81))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_27 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_27.setObjectName("gridImg")
        pixmap = QPixmap('data/images/profit.png')
        pixmap = pixmap.scaledToWidth(85)
        self.label_27.setPixmap(pixmap)
        self.label_27.mousePressEvent = self.labelClick9
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout_5.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_28.setObjectName("gridImg")
        pixmap = QPixmap('data/images/addStaff.png')
        pixmap = pixmap.scaledToWidth(85)
        self.label_28.setPixmap(pixmap)
        self.label_28.mousePressEvent = self.labelClick10
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout_5.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_29.setObjectName("gridImg")
        pixmap = QPixmap('data/images/viewStaff.png')
        pixmap = pixmap.scaledToWidth(85)
        self.label_29.setPixmap(pixmap)
        self.label_29.mousePressEvent = self.labelClick11
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout_5.addWidget(self.label_29)

        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_12.setObjectName("gridImg")
        pixmap = QPixmap('data/images/graph.png')
        pixmap = pixmap.scaledToWidth(88)
        self.label_12.setPixmap(pixmap)
        self.label_12.mousePressEvent = self.labelClick15
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_5.addWidget(self.label_12)
        self.label_12.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(50, 480, 811, 31))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_31 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_31.setObjectName("gridText")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_6.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_32.setObjectName("gridText")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_6.addWidget(self.label_32)
        self.label_33 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_33.setObjectName("gridText")
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_6.addWidget(self.label_33)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_13.setObjectName("gridText")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 132, 920, 2))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("adminLine")
        self.horizontalLayout_6.addWidget(self.label_13)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 914, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Admin Menu | UG - Pharmacy Management System"))

        self.label.setText(_translate("MainWindow", "UG - PHARMACY MS"))
        self.logoutBTN.setText(_translate("MainWindow", "Logout"))

        self.label_2.setText(_translate("MainWindow", "Admin Main Menu"))
        self.label_9.setText(_translate("MainWindow", ""))
        self.label_14.setText(_translate("MainWindow", ""))
        self.label_6.setText(_translate("MainWindow", ""))

        self.label_7.setText(_translate("MainWindow", ""))
        self.label_8.setText(_translate("MainWindow", "Sold On Credit"))
        self.label_10.setText(_translate("MainWindow", ""))
        self.label_11.setText(_translate("MainWindow", "Credit Sales Cleared"))
        self.label_12.setText(_translate("MainWindow", ""))
        self.label_13.setText(_translate("MainWindow", "Graphs / Reports"))
        self.label_24.setText(_translate("MainWindow", "Add Stock"))
        self.label_17.setText(_translate("MainWindow", "View Stock"))
        self.label_16.setText(_translate("MainWindow", "View Sales"))

        self.label_26.setText(_translate("MainWindow", "View Expenditure"))
        self.label_18.setText(_translate("MainWindow", "Stock To Reorder"))
        self.label_19.setText(_translate("MainWindow", "Soon to Expire"))

        self.label_25.setText(_translate("MainWindow", ""))
        self.label_21.setText(_translate("MainWindow", ""))
        self.label_22.setText(_translate("MainWindow", ""))

        self.label_27.setText(_translate("MainWindow", ""))
        self.label_28.setText(_translate("MainWindow", ""))
        self.label_29.setText(_translate("MainWindow", ""))

        self.label_31.setText(_translate("MainWindow", "Profit / Loss"))
        self.label_32.setText(_translate("MainWindow", "Add Staff"))
        self.label_33.setText(_translate("MainWindow", "View Staff"))


    def logOut(self):
        # opening a user window
        #self.hide()
        self.window = QtWidgets.QMainWindow()
        self.userMObj = PL.Ui_Login()
        self.userMObj.setupUi(self.window)
        self.window.show()
        MainWindow.hide()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_adminMenu()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

