from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QCursor
from PyQt5.QtGui import QIcon, QPixmap
class Ui_clearCredit(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(448, 411)
        self.setWindowFlags(QtCore.Qt.Window)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 70, 411, 191))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.billNumberLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.billNumberLabel.setObjectName("sellLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.billNumberLabel)
        self.billNumberLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.billNumberLineEdit.setObjectName("billNumberLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.billNumberLineEdit)
        self.clientNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.clientNameLabel.setObjectName("sellLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.clientNameLabel)
        self.clientNameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.clientNameLineEdit.setObjectName("clientNameLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.clientNameLineEdit)
        self.billLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.billLabel.setObjectName("sellLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.billLabel)
        self.billLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.billLineEdit.setObjectName("billLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.billLineEdit)
        self.amountPaidLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.amountPaidLabel.setObjectName("sellLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.amountPaidLabel)
        self.amountPaidLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.amountPaidLineEdit.setObjectName("amountPaidLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.amountPaidLineEdit)
        self.balanceLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.balanceLabel.setObjectName("sellLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.balanceLabel)
        self.balanceLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.balanceLineEdit.setObjectName("balanceLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.balanceLineEdit)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 400, 31))
        self.label.setObjectName("sellTitle")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 250, 291, 31))
        self.label_2.setObjectName("qtnLabel")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(80, 290, 291, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(144, 340, 161, 41))
        self.pushButton.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("sellBTN")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Pay Debt"))
        Dialog.setWindowIcon(QIcon('data/images/logoicon.ICO'))
        self.billNumberLabel.setText(_translate("Dialog", "Bill Number :"))
        self.clientNameLabel.setText(_translate("Dialog", "Client Name :"))
        self.billLabel.setText(_translate("Dialog", "Bill"))
        self.amountPaidLabel.setText(_translate("Dialog", "Amount Paid"))
        self.balanceLabel.setText(_translate("Dialog", "Balance : "))
        self.label.setText(_translate("Dialog", "Clear Debt"))
        self.label_2.setText(_translate("Dialog", "Enter Amount"))
        self.pushButton.setText(_translate("Dialog", "Pay Debt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_clearCredit()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

