from PyQt5.QtGui import QCursor
from PyQt5.QtGui import QIcon, QPixmap
from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_updateUser(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        self.setWindowFlags(QtCore.Qt.Window)
        Dialog.setFixedSize(754, 573)
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(20, 3, 711, 31))
        self.title.setObjectName("mtitle")
        self.username = QtWidgets.QLabel(Dialog)
        self.username.setGeometry(QtCore.QRect(800, 20, 47, 13))
        self.username.setText("")
        self.username.setObjectName("username")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(250, 70, 2, 481))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(490, 70, 2, 291))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 39, 221, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(260, 39, 221, 31))
        self.label_2.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(500, 39, 231, 31))
        self.label_3.setObjectName("label")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 70, 221, 491))
        self.widget.setObjectName("widget")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 221, 31))
        self.label_4.setObjectName("sellLabel")
        self.uname = QtWidgets.QLineEdit(self.widget)
        self.uname.setGeometry(QtCore.QRect(0, 30, 221, 31))
        self.uname.setObjectName("uname")
        self.fName = QtWidgets.QLineEdit(self.widget)
        self.fName.setGeometry(QtCore.QRect(0, 100, 221, 31))
        self.fName.setObjectName("fName")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(0, 70, 221, 31))
        self.label_5.setObjectName("sellLabel")
        self.lName = QtWidgets.QLineEdit(self.widget)
        self.lName.setGeometry(QtCore.QRect(0, 170, 221, 31))
        self.lName.setObjectName("lName")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(0, 140, 221, 31))
        self.label_6.setObjectName("sellLabel")
        self.dob = QtWidgets.QLineEdit(self.widget)
        self.dob.setGeometry(QtCore.QRect(0, 240, 221, 31))
        self.dob.setObjectName("dob")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(0, 210, 221, 31))
        self.label_7.setObjectName("sellLabel")
        self.sex = QtWidgets.QComboBox(self.widget)
        self.sex.setGeometry(QtCore.QRect(0, 310, 221, 31))
        self.sex.setObjectName("sex")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(0, 280, 221, 31))
        self.label_8.setObjectName("sellLabel")
        self.status = QtWidgets.QComboBox(self.widget)
        self.status.setGeometry(QtCore.QRect(0, 380, 221, 31))
        self.status.setObjectName("status")

        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(0, 350, 221, 31))
        self.label_9.setObjectName("sellLabel")
        self.kinName = QtWidgets.QLineEdit(self.widget)
        self.kinName.setGeometry(QtCore.QRect(0, 450, 221, 31))
        self.kinName.setObjectName("kinName")
        self.label_22 = QtWidgets.QLabel(self.widget)
        self.label_22.setGeometry(QtCore.QRect(0, 420, 221, 31))
        self.label_22.setObjectName("sellLabel")
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setGeometry(QtCore.QRect(260, 70, 221, 491))
        self.widget_2.setObjectName("widget_2")
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 221, 31))
        self.label_10.setObjectName("sellLabel")
        self.nationalID = QtWidgets.QLineEdit(self.widget_2)
        self.nationalID.setGeometry(QtCore.QRect(0, 30, 221, 31))
        self.nationalID.setObjectName("nationalID")
        self.homeDist = QtWidgets.QLineEdit(self.widget_2)
        self.homeDist.setGeometry(QtCore.QRect(0, 100, 221, 31))
        self.homeDist.setObjectName("homeDist")
        self.label_11 = QtWidgets.QLabel(self.widget_2)
        self.label_11.setGeometry(QtCore.QRect(0, 70, 221, 31))
        self.label_11.setObjectName("sellLabel")
        self.currentDist = QtWidgets.QLineEdit(self.widget_2)
        self.currentDist.setGeometry(QtCore.QRect(0, 170, 221, 31))
        self.currentDist.setObjectName("currentDist")
        self.label_12 = QtWidgets.QLabel(self.widget_2)
        self.label_12.setGeometry(QtCore.QRect(0, 140, 221, 31))
        self.label_12.setObjectName("sellLabel")
        self.currentAddress = QtWidgets.QLineEdit(self.widget_2)
        self.currentAddress.setGeometry(QtCore.QRect(0, 240, 221, 31))
        self.currentAddress.setObjectName("currentAddress")
        self.label_13 = QtWidgets.QLabel(self.widget_2)
        self.label_13.setGeometry(QtCore.QRect(0, 210, 221, 31))
        self.label_13.setObjectName("sellLabel")
        self.phone = QtWidgets.QLineEdit(self.widget_2)
        self.phone.setGeometry(QtCore.QRect(0, 310, 221, 31))
        self.phone.setObjectName("phone")
        self.label_14 = QtWidgets.QLabel(self.widget_2)
        self.label_14.setGeometry(QtCore.QRect(0, 280, 221, 31))
        self.label_14.setObjectName("sellLabel")
        self.yoEmail = QtWidgets.QLineEdit(self.widget_2)
        self.yoEmail.setGeometry(QtCore.QRect(0, 380, 221, 31))
        self.yoEmail.setObjectName("yoEmail")
        self.label_15 = QtWidgets.QLabel(self.widget_2)
        self.label_15.setGeometry(QtCore.QRect(0, 350, 221, 31))
        self.label_15.setObjectName("sellLabel")
        self.kinPhone = QtWidgets.QLineEdit(self.widget_2)
        self.kinPhone.setGeometry(QtCore.QRect(0, 450, 221, 31))
        self.kinPhone.setObjectName("kinPhone")
        self.label_23 = QtWidgets.QLabel(self.widget_2)
        self.label_23.setGeometry(QtCore.QRect(0, 420, 221, 31))
        self.label_23.setObjectName("sellLabel")
        self.widget_3 = QtWidgets.QWidget(Dialog)
        self.widget_3.setGeometry(QtCore.QRect(500, 70, 231, 281))
        self.widget_3.setObjectName("widget_3")
        self.label_16 = QtWidgets.QLabel(self.widget_3)
        self.label_16.setGeometry(QtCore.QRect(0, 0, 221, 31))
        self.label_16.setObjectName("sellLabel")
        self.salary = QtWidgets.QLineEdit(self.widget_3)
        self.salary.setGeometry(QtCore.QRect(0, 30, 221, 31))
        self.salary.setObjectName("salary")
        self.joinDate = QtWidgets.QLineEdit(self.widget_3)
        self.joinDate.setGeometry(QtCore.QRect(0, 100, 221, 31))
        self.joinDate.setObjectName("joinDate")
        self.label_17 = QtWidgets.QLabel(self.widget_3)
        self.label_17.setGeometry(QtCore.QRect(0, 70, 211, 31))
        self.label_17.setObjectName("sellLabel")
        self.pass1 = QtWidgets.QLineEdit(self.widget_3)
        self.pass1.setGeometry(QtCore.QRect(0, 170, 221, 31))
        self.pass1.setObjectName("pass1")
        self.label_18 = QtWidgets.QLabel(self.widget_3)
        self.label_18.setGeometry(QtCore.QRect(0, 140, 211, 31))
        self.label_18.setObjectName("sellLabel")
        self.pass2 = QtWidgets.QLineEdit(self.widget_3)
        self.pass2.setGeometry(QtCore.QRect(0, 240, 221, 31))
        self.pass2.setObjectName("pass2")
        self.label_19 = QtWidgets.QLabel(self.widget_3)
        self.label_19.setGeometry(QtCore.QRect(0, 210, 271, 31))
        self.label_19.setObjectName("sellLabel")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(490, 360, 241, 2))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line")
        self.updateAccBTN2 = QtWidgets.QPushButton(Dialog)
        self.updateAccBTN2.setGeometry(QtCore.QRect(520, 380, 191, 61))
        self.updateAccBTN2.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.updateAccBTN2.setObjectName("sellBTN")
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)



    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Update Staff Member "))
        Dialog.setWindowIcon(QIcon('data/images/logoicon.ICO'))
        self.title.setText(_translate("Dialog", "Update Staff Member"))
        self.label.setText(_translate("Dialog", "Bio Data"))
        self.label_2.setText(_translate("Dialog", "Contacts"))
        self.label_3.setText(_translate("Dialog", "Password Section"))
        self.label_4.setText(_translate("Dialog", "Username*"))
        self.label_5.setText(_translate("Dialog", "First Name*"))
        self.label_6.setText(_translate("Dialog", "Last Name*"))
        self.label_7.setText(_translate("Dialog", "Date Of Birth*"))
        self.label_8.setText(_translate("Dialog", "Sex*"))
        self.label_9.setText(_translate("Dialog", "Status*"))
        self.label_22.setText(_translate("Dialog", "Next Of Kin*"))
        self.label_10.setText(_translate("Dialog", "National ID*"))
        self.label_11.setText(_translate("Dialog", "Home District*"))
        self.label_12.setText(_translate("Dialog", "Current District*"))
        self.label_13.setText(_translate("Dialog", "Current Address*"))
        self.label_14.setText(_translate("Dialog", "Phone Number*"))
        self.label_15.setText(_translate("Dialog", "Email Address"))
        self.label_23.setText(_translate("Dialog", "Next Of Kin Contact*"))
        self.label_16.setText(_translate("Dialog", "Salary "))
        self.label_17.setText(_translate("Dialog", "Joining Date"))
        self.label_18.setText(_translate("Dialog", "Password*"))
        self.label_19.setText(_translate("Dialog", "Confirm Password*"))
        self.updateAccBTN2.setText(_translate("Dialog", "ADD USER"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_updateUser()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

