from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QCursor
from PyQt5.QtGui import QIcon, QPixmap
class Ui_updateStock(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(448, 411)
        self.setWindowFlags(QtCore.Qt.Window)

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 395, 31))
        self.label.setObjectName("sellTitle")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(20, 350, 181, 41))
        self.pushButton.setObjectName("sellBTN")
        self.pushButton.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 50, 401, 301))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.drugNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.drugNameLabel.setObjectName("sellLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.drugNameLabel)
        self.drugNameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.drugNameLineEdit.setObjectName("drugNameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.drugNameLineEdit)
        self.batchNumberLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.batchNumberLabel.setObjectName("sellLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.batchNumberLabel)
        self.batchNumberLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.batchNumberLineEdit.setObjectName("batchNumberLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.batchNumberLineEdit)
        self.categoryLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.categoryLabel.setObjectName("sellLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.categoryLabel)
        self.categoryLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.categoryLineEdit.setObjectName("categoryLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.categoryLineEdit)
        self.quantityLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.quantityLabel.setObjectName("sellLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.quantityLabel)
        self.quantityLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.quantityLineEdit.setObjectName("quantityLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.quantityLineEdit)
        self.buyingPriceLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.buyingPriceLabel.setObjectName("sellLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.buyingPriceLabel)
        self.buyingPriceLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.buyingPriceLineEdit.setObjectName("buyingPriceLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.buyingPriceLineEdit)
        self.sellingPriceLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.sellingPriceLabel.setObjectName("sellLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.sellingPriceLabel)
        self.sellingPriceLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.sellingPriceLineEdit.setObjectName("sellingPriceLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.sellingPriceLineEdit)
        self.supplierLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.supplierLabel.setObjectName("sellLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.supplierLabel)
        self.supplierLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.supplierLineEdit.setObjectName("supplierLineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.supplierLineEdit)
        self.productionDateLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.productionDateLabel.setObjectName("sellLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.productionDateLabel)
        self.productionDateDateEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.productionDateDateEdit.setObjectName("productionDateDateEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.productionDateDateEdit)
        self.expireDateLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.expireDateLabel.setObjectName("sellLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.expireDateLabel)

        self.expireDateLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.expireDateLineEdit.setObjectName("expireDateLineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.expireDateLineEdit)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 350, 191, 41))
        self.pushButton_2.setObjectName("profitBTN")
        self.pushButton_2.setCursor(QCursor(QtCore.Qt.PointingHandCursor))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Update / Delete "))
        Dialog.setWindowIcon(QIcon('data/images/logoicon.ICO'))
        self.label.setText(_translate("Dialog", "Update and Delete From Stock"))
        self.pushButton.setText(_translate("Dialog", "Update Drug"))
        self.drugNameLabel.setText(_translate("Dialog", "Drug Name : "))
        self.batchNumberLabel.setText(_translate("Dialog", "Batch Number :"))
        self.categoryLabel.setText(_translate("Dialog", "Category"))
        self.quantityLabel.setText(_translate("Dialog", "Quantity :"))
        self.buyingPriceLabel.setText(_translate("Dialog", "Buying Price :"))
        self.sellingPriceLabel.setText(_translate("Dialog", "Selling Price"))
        self.supplierLabel.setText(_translate("Dialog", "Supplier :"))
        self.productionDateLabel.setText(_translate("Dialog", "Reorder Level :"))
        self.expireDateLabel.setText(_translate("Dialog", "Expire Date :"))
        self.pushButton_2.setText(_translate("Dialog", "Delete Drug"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_updateStock()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

