from PyQt5 import QtCore, QtGui, QtWidgets
import pharmacyLoginController as PLC
from PyQt5.QtGui import QCursor
from PyQt5.QtGui import QIcon, QPixmap
class Ui_userMenu():
    def __init__(self):
        global userID,uname2
        userID = PLC.pharmacyLoginController.getUserID()
        uname2 = PLC.pharmacyLoginController.getUsername()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("adminMenuBody")
        MainWindow.setFixedSize(914, 595)
        self.setWindowFlag(QtCore.Qt.WindowCloseButtonHint, False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.img2 = QtWidgets.QLabel(self.centralwidget)
        pixmap = QPixmap('data/images/logoInner.png')
        self.img2.setPixmap(pixmap)
        self.img2.setGeometry(QtCore.QRect(50, 10, 121, 121))
        self.img2.setScaledContents(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.img2.setFont(font)
        self.img2.setScaledContents(True)
        self.img2.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 20, 500, 46))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("title1")
        self.logoutBTN = QtWidgets.QPushButton(self.centralwidget)
        self.logoutBTN.setGeometry(QtCore.QRect(770, 20, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.logoutBTN.setFont(font)
        self.logoutBTN.setObjectName("logoutBTN")
        self.logoutBTN.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 520, 920, 2))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("adminLine")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 540, 381, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("footerText")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setGeometry(QtCore.QRect(250, 100, 491, 30))
        self.label_2.setObjectName("header1")

        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 150, 811, 135))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_14.setObjectName("gridImg2")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        pixmap = QPixmap('data/images/sales.png')
        pixmap = pixmap.scaledToWidth(135)
        self.label_14.setPixmap(pixmap)
        self.label_14.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.label_14.mousePressEvent = self.labelClick1
        self.horizontalLayout.addWidget(self.label_14)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName("gridImg2")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        pixmap = QPixmap('data/images/exp.png')
        pixmap = pixmap.scaledToWidth(135)
        self.label_6.setPixmap(pixmap)
        self.label_6.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.label_6.mousePressEvent = self.labelClick2
        self.horizontalLayout.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("gridImg2")
        self.label_5.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        pixmap = QPixmap('data/images/addDrug.png')
        pixmap = pixmap.scaledToWidth(142)
        self.label_5.setPixmap(pixmap)
        self.label_5.mousePressEvent = self.labelClick3
        self.horizontalLayout.addWidget(self.label_5)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(50, 285, 811, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_17.setObjectName("gridText")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_2.addWidget(self.label_17)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_16.setObjectName("gridText")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_2.addWidget(self.label_16)
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_15.setObjectName("gridText")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_2.addWidget(self.label_15)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(50, 475, 811, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_18.setObjectName("gridText")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_3.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_19.setObjectName("gridText")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_3.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_20.setObjectName("gridText")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_3.addWidget(self.label_20)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(50, 340, 811, 135))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_21.setObjectName("gridImg2")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        pixmap = QPixmap('data/images/credit.png')
        pixmap = pixmap.scaledToWidth(145)
        self.label_21.setPixmap(pixmap)
        self.label_21.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.label_21.mousePressEvent = self.labelClick4
        self.horizontalLayout_4.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_22.setObjectName("gridImg2")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        pixmap = QPixmap('data/images/userExp.png')
        pixmap = pixmap.scaledToWidth(145)
        self.label_22.setPixmap(pixmap)
        self.label_22.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.label_22.mousePressEvent = self.labelClick5
        self.horizontalLayout_4.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_23.setObjectName("gridImg2")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        pixmap = QPixmap('data/images/acc.png')
        pixmap = pixmap.scaledToWidth(130)
        self.label_23.setPixmap(pixmap)
        self.label_23.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.label_23.mousePressEvent = self.labelClick6
        self.horizontalLayout_4.addWidget(self.label_23)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 132, 920, 2))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("adminLine")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 914, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Staff Menu | UG - Pharmacy Management System"))

        self.label.setText(_translate("MainWindow", "UG - PHARMACY MS"))
        self.logoutBTN.setText(_translate("MainWindow", "Logout"))
        self.label_4.setText(_translate("MainWindow", "Developed By Micheal UCU 2020"))
        self.label_2.setText(_translate("MainWindow", "Staff Main Menu"))
        self.label_14.setText(_translate("MainWindow", ""))
        self.label_6.setText(_translate("MainWindow", ""))
        self.label_5.setText(_translate("MainWindow", ""))
        self.label_17.setText(_translate("MainWindow", "Sale"))
        self.label_16.setText(_translate("MainWindow", "Expenditure"))
        self.label_15.setText(_translate("MainWindow", "mmmmmmm"))
        self.label_18.setText(_translate("MainWindow", "Sold On Credit"))
        self.label_19.setText(_translate("MainWindow", "View Expenditure"))
        self.label_20.setText(_translate("MainWindow", "Your Account"))
        self.label_21.setText(_translate("MainWindow", ""))
        self.label_22.setText(_translate("MainWindow", ""))
        self.label_23.setText(_translate("MainWindow", ""))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)

    MainWindow1 = QtWidgets.QMainWindow()
    ui = Ui_userMenu()
    ui.setupUi(MainWindow1)
    MainWindow1.show()
    sys.exit(app.exec_())
